sudo: required
language: node_js
node_js:
  - "0.8"
  - "0.10"
services:
  - mongodb
  
before_install:
    - "curl https://install.meteor.com | /bin/sh"
    - "meteor reset"
    - "meteor -p 3000 &"
  
#script:
 # bash test.sh


